name: "Compile and run unit tests"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
    - name: Run tests
      run: "nix-shell --pure --run 'sbt test'"
    - name: Ensure notes are being created
      run: "nix-shell --pure --run 'mkdocs build'"
